"""changed column name mp3 url

Revision ID: 8c457b25ad0c
Revises: a51d072f12b1
Create Date: 2022-08-02 14:27:34.386721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c457b25ad0c'
down_revision = 'a51d072f12b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('mp3_url', sa.String(length=255), nullable=False))
    op.drop_column('songs', 'mp3_Url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('mp3_Url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('songs', 'mp3_url')
    # ### end Alembic commands ###
