"""added column song

Revision ID: 7d5e8642e8d8
Revises: 8c457b25ad0c
Create Date: 2022-08-03 00:09:13.165464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d5e8642e8d8'
down_revision = '8c457b25ad0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'image_url')
    # ### end Alembic commands ###
